export const articles = [
  {
    id: 1,
    title: "Lorem ipsum dolor sit amet",
    abstract:
      "Sed dignissim lacinia nunc. Curabitur tortor. Pellentesque nibh. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh.",
    content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus non libero id sapien eleifend maximus. Sed faucibus vestibulum tellus, volutpat euismod dui maximus eu. Donec blandit vulputate nisi ac accumsan. Etiam finibus, massa vitae sodales tristique, arcu odio posuere mi, sit amet dictum nibh lacus id lorem. Morbi mollis sed nulla a scelerisque. Sed vehicula tempor venenatis. Integer nec libero ipsum. Ut semper eros in mattis molestie.

Nulla eget ex diam. Mauris mauris lorem, fringilla eget nisi feugiat, finibus tempus metus. Maecenas non scelerisque sapien. Suspendisse dignissim scelerisque metus eu vestibulum. Aenean ultricies ullamcorper ullamcorper. Pellentesque fringilla turpis augue, eget lacinia felis lacinia eu. Proin luctus ex in metus tempor elementum. Cras egestas arcu ut convallis bibendum. Morbi quis commodo enim. Cras sit amet accumsan tellus, eu vulputate purus. Nullam pellentesque risus at felis eleifend, fringilla scelerisque nisi vehicula. Ut at rutrum lorem.

Praesent id odio ut massa venenatis tempus ut id lacus. Etiam hendrerit accumsan orci, sed aliquet justo euismod eget. Cras aliquam justo sit amet tempor rutrum. Morbi ultricies elit at pulvinar consequat. Morbi condimentum sem et vehicula bibendum. Nulla mi ante, accumsan in elit id, maximus malesuada elit. Quisque rhoncus quis justo in fringilla. Nullam sed suscipit mi. Proin at rutrum purus, non egestas orci. Phasellus facilisis tellus luctus tempus porttitor. Cras elementum enim eu placerat rhoncus. Sed sollicitudin eget dolor in tempor. Nullam interdum sed tortor eu feugiat. Nam nulla tellus, euismod sagittis mollis at, convallis accumsan risus. Praesent fringilla, ex in fermentum vulputate, leo augue porta orci, ac consectetur neque orci eget ligula.

Nunc auctor a nisi vitae luctus. Phasellus vehicula tincidunt dapibus. In lobortis nisi ac sem accumsan, sed rhoncus nunc viverra. Aliquam erat volutpat. Proin ac odio felis. Aliquam finibus consectetur tempus. Aenean ullamcorper eget felis a posuere. Nulla mollis lectus neque, sit amet laoreet nisi facilisis sed. Nullam vitae justo posuere, malesuada felis ac, sodales ex. Sed varius, ante sed pretium eleifend, augue lacus volutpat diam, sed suscipit odio metus in nunc.

Vivamus volutpat suscipit massa, auctor consequat arcu viverra a. Suspendisse dictum molestie pretium. Suspendisse bibendum ultricies elit eu faucibus. Morbi posuere nisi ex. Praesent rhoncus rhoncus mi a sollicitudin. Phasellus mi nunc, molestie sit amet justo quis, volutpat lacinia velit. Sed posuere lorem non nisl lacinia porta. Etiam eget sodales sem. Nam sodales, mi vitae egestas hendrerit, neque risus vehicula nulla, quis posuere nulla justo a mauris.`,
  },
  {
    id: 2,
    title: "consectetur adipiscing elit",
    abstract:
      "uisque volutpat condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. Proin quam. Etiam ultrices. Suspendisse in justo eu magna luctus suscipit. Sed lectus. Integer euismod lacus luctus magna. ",
    content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus non libero id sapien eleifend maximus. Sed faucibus vestibulum tellus, volutpat euismod dui maximus eu. Donec blandit vulputate nisi ac accumsan. Etiam finibus, massa vitae sodales tristique, arcu odio posuere mi, sit amet dictum nibh lacus id lorem. Morbi mollis sed nulla a scelerisque. Sed vehicula tempor venenatis. Integer nec libero ipsum. Ut semper eros in mattis molestie.

Nulla eget ex diam. Mauris mauris lorem, fringilla eget nisi feugiat, finibus tempus metus. Maecenas non scelerisque sapien. Suspendisse dignissim scelerisque metus eu vestibulum. Aenean ultricies ullamcorper ullamcorper. Pellentesque fringilla turpis augue, eget lacinia felis lacinia eu. Proin luctus ex in metus tempor elementum. Cras egestas arcu ut convallis bibendum. Morbi quis commodo enim. Cras sit amet accumsan tellus, eu vulputate purus. Nullam pellentesque risus at felis eleifend, fringilla scelerisque nisi vehicula. Ut at rutrum lorem.

Praesent id odio ut massa venenatis tempus ut id lacus. Etiam hendrerit accumsan orci, sed aliquet justo euismod eget. Cras aliquam justo sit amet tempor rutrum. Morbi ultricies elit at pulvinar consequat. Morbi condimentum sem et vehicula bibendum. Nulla mi ante, accumsan in elit id, maximus malesuada elit. Quisque rhoncus quis justo in fringilla. Nullam sed suscipit mi. Proin at rutrum purus, non egestas orci. Phasellus facilisis tellus luctus tempus porttitor. Cras elementum enim eu placerat rhoncus. Sed sollicitudin eget dolor in tempor. Nullam interdum sed tortor eu feugiat. Nam nulla tellus, euismod sagittis mollis at, convallis accumsan risus. Praesent fringilla, ex in fermentum vulputate, leo augue porta orci, ac consectetur neque orci eget ligula.

Nunc auctor a nisi vitae luctus. Phasellus vehicula tincidunt dapibus. In lobortis nisi ac sem accumsan, sed rhoncus nunc viverra. Aliquam erat volutpat. Proin ac odio felis. Aliquam finibus consectetur tempus. Aenean ullamcorper eget felis a posuere. Nulla mollis lectus neque, sit amet laoreet nisi facilisis sed. Nullam vitae justo posuere, malesuada felis ac, sodales ex. Sed varius, ante sed pretium eleifend, augue lacus volutpat diam, sed suscipit odio metus in nunc.

Vivamus volutpat suscipit massa, auctor consequat arcu viverra a. Suspendisse dictum molestie pretium. Suspendisse bibendum ultricies elit eu faucibus. Morbi posuere nisi ex. Praesent rhoncus rhoncus mi a sollicitudin. Phasellus mi nunc, molestie sit amet justo quis, volutpat lacinia velit. Sed posuere lorem non nisl lacinia porta. Etiam eget sodales sem. Nam sodales, mi vitae egestas hendrerit, neque risus vehicula nulla, quis posuere nulla justo a mauris.`,
  },
  {
    id: 3,
    title: "Praesent libero. Sed cursus ante dapibus diam",
    abstract:
      "Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi lacinia molestie dui. Praesent blandit dolor. Sed non quam. In vel mi sit amet augue congue elementum. Morbi in ipsum sit amet pede facilisis laoreet. Donec lacus nunc, viverra nec, blandit vel, egestas et, augue. Vestibulum tincidunt malesuada tellus. Ut ultrices ultrices enim. Curabitur sit amet mauris. Morbi in dui quis est pulvinar ullamcorper. Nulla facilisi. Integer lacinia sollicitudin massa. Cras metus.",
    content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus non libero id sapien eleifend maximus. Sed faucibus vestibulum tellus, volutpat euismod dui maximus eu. Donec blandit vulputate nisi ac accumsan. Etiam finibus, massa vitae sodales tristique, arcu odio posuere mi, sit amet dictum nibh lacus id lorem. Morbi mollis sed nulla a scelerisque. Sed vehicula tempor venenatis. Integer nec libero ipsum. Ut semper eros in mattis molestie.

Nulla eget ex diam. Mauris mauris lorem, fringilla eget nisi feugiat, finibus tempus metus. Maecenas non scelerisque sapien. Suspendisse dignissim scelerisque metus eu vestibulum. Aenean ultricies ullamcorper ullamcorper. Pellentesque fringilla turpis augue, eget lacinia felis lacinia eu. Proin luctus ex in metus tempor elementum. Cras egestas arcu ut convallis bibendum. Morbi quis commodo enim. Cras sit amet accumsan tellus, eu vulputate purus. Nullam pellentesque risus at felis eleifend, fringilla scelerisque nisi vehicula. Ut at rutrum lorem.

Praesent id odio ut massa venenatis tempus ut id lacus. Etiam hendrerit accumsan orci, sed aliquet justo euismod eget. Cras aliquam justo sit amet tempor rutrum. Morbi ultricies elit at pulvinar consequat. Morbi condimentum sem et vehicula bibendum. Nulla mi ante, accumsan in elit id, maximus malesuada elit. Quisque rhoncus quis justo in fringilla. Nullam sed suscipit mi. Proin at rutrum purus, non egestas orci. Phasellus facilisis tellus luctus tempus porttitor. Cras elementum enim eu placerat rhoncus. Sed sollicitudin eget dolor in tempor. Nullam interdum sed tortor eu feugiat. Nam nulla tellus, euismod sagittis mollis at, convallis accumsan risus. Praesent fringilla, ex in fermentum vulputate, leo augue porta orci, ac consectetur neque orci eget ligula.

Nunc auctor a nisi vitae luctus. Phasellus vehicula tincidunt dapibus. In lobortis nisi ac sem accumsan, sed rhoncus nunc viverra. Aliquam erat volutpat. Proin ac odio felis. Aliquam finibus consectetur tempus. Aenean ullamcorper eget felis a posuere. Nulla mollis lectus neque, sit amet laoreet nisi facilisis sed. Nullam vitae justo posuere, malesuada felis ac, sodales ex. Sed varius, ante sed pretium eleifend, augue lacus volutpat diam, sed suscipit odio metus in nunc.

Vivamus volutpat suscipit massa, auctor consequat arcu viverra a. Suspendisse dictum molestie pretium. Suspendisse bibendum ultricies elit eu faucibus. Morbi posuere nisi ex. Praesent rhoncus rhoncus mi a sollicitudin. Phasellus mi nunc, molestie sit amet justo quis, volutpat lacinia velit. Sed posuere lorem non nisl lacinia porta. Etiam eget sodales sem. Nam sodales, mi vitae egestas hendrerit, neque risus vehicula nulla, quis posuere nulla justo a mauris.`,
  },
];
